twitter:
  api_key: "yourKey"
  api_secret: "yourSecret"
  access_token: "yourToken"
  access_token_secret: "yourTokenSecret"
  app_auth_url: "https://api.twitter.com/oauth2/token"
  request_token_url: "https://api.twitter.com/oauth/request_token"
  authorize_secure_url: "https://api.twitter.com/oauth/authorize"
  access_token_url: "https://api.twitter.com/oauth/access_token"
  rest_api_url: "https://api.twitter.com/"
  searchTerms:
    - "bitcoin,btc"
    - "bitcoin cash,bcc,bch"
    - "bitcoin gold,btg,bcg"
    - "litecoin,ltc"
    - "augur,$rep"
    - "ardor,ardr"
    - "belacoin,#bela,$bela"
    - "bitcoindark,btcd"
    - "bitcoinplus,xbc"
    - "bitshares,$bts"
    - "bitmark,btm"
    - "bytecoin,bcn"
    - "#burst, $burst"
    - "clams,clam"
    - "dash"
    - "decred,dcr"
    - "digibyte,dgb"
    - "dnotes,$note"
    - "dogecoin,$doge"
    - "einsteinium,$emc2"
    - "ethereum classic,$etc"
    - "ethereum,eth"
    - "expanse,$exp"
    - "factom,$fct"
    - "florincoin,$flo"
    - "foldingcoin,$fldc"
    - "gameCredits"
    - "golem,$gnt"
    - "gridcoin,$grc"
    - "lbry,lbc,lbrycredits"
    - "lisk,$lsk"
    - "maidsafecoin,maidsafe,$maid"
    - "monero,$xmr"
    - "namecoin,$nmc"
    - "nautiluscoin,$naut"
    - "navcoin,$nav"
    - "#nem,$xem"
    - "neoscoin,$neos"
    - "$nxt"
    - "omni"
    - "pascalcoin,$pasc"
    - "peercoin,$ppc"
    - "pinkcoin,$pink"
    - "potcoin,$pot"
    - "primecoin,$xpm"
    - "radium,$rads"
    - "riecoin,$ric"
    - "ripple,$xrp"
    - "siacoin,$sc"
    - "steem"
    - "steemdollars,$sbd"
    - "stellar,$str"
    - "storjcoin,sjcx"
    - "stratis,$strat"
    - "synereo,$amp"
    - "syscoin,$sys"
    - "vericoin,$vrc"
    - "vertcoin,$vtc"
    - "viacoin,$via"
    - "zcash,$zec"
  userStreams:
    - bitcoin
    - litecoin
    - AugurProject
    - ArdorPlatform
    - LetsLiveBela
    - BitcoinDark‏
    - BitcoinPlusOrg
    - Ripple
    - Bytecoin_BCN
    - DigiByteCoin
    - coinbase
    - gdax
    - okcoin
    - Cryptopia_NZ
    - huobicom
    - bitshares
    - TuurDemeester
    - VitalikButerin
    - ProjectBitmark
    - BitmarkUpdates
    - BitmarkInc
    - Burstcoin_dev
    - ClamClient
    - Dashpay
    - decredproject
    - DNotesCoin
    - dogecoin
    - einsteiniumcoin
    - Emc2CoinHQ
    - EthereumClassic
    - eth_classic
    - ethereumproject
    - gavofyork
    - expanseofficial
    - factom
    - Official_Florin
    - FlorincoinPR
    - FoldingCoin
    - theJonesD
    - GameCredit
    - SatoshiLite
    - TheRealXinxi
    - kimDotCom
    - golemproject
    - GridcoinNetwork
    - monerocurrency
    - LBRYio
    - LiskHQ
    - maidsafe
    - Namecoin
    - Nautiluscoin
    - Nautcointeam
    - NAVCoin
    - nemofficial
    - NeosCoin
    - nxtcommunity
    - Omni_Layer
    - PascalCoin
    - PeercoinPPC
    - Pinkcoin
    - PotCoin
    - Primecoin
    - RadiumCore
    - riecoin
    - SiaTechHQ
    - SteemServices
    - SteemStarter
    - stellarOrg
    - storjproject
    - storjlabs
    - storjdev
    - stratisplatform
    - Synereo
    - syscoin
    - VeriCoin
    - Vertcoin
    - viacoin
    - zcashco
    - NickSzabo4
    - whalePanda
    - bitfinex
    - Lightning
    - Bitstamp
    - bitwage
    - krakenfx
    - LocalBitcoins
    - xapo
    - cnLedger
    - GeminiDotCom
    - Coinfloor
    - jaxx_io
    - 2017Lon
    - PaulRieger
    - NEMofficial
    - ErikVoorhees
    - ShapeShift_io
    - ExceIlion
    - MicreeZ
    - tdryja
    - rusty_twit
    - Toshy_desk
    - HyperLedger
    - JackMallers
    - BittrexExchange
    - BITMainTech
    - LTCFoundation
    - LitecoinProject
    - roasbeef
    - johnsonlau01
    - tonilanec
    - bramcohen
    - surrealtc
    - SatoshiLite
    - bvu
    - starkness
    - rogerkver

reddit:
  secret: ""
  appName: "commentMiner"
  app_auth_url: https://www.reddit.com/api/v1/authorize?client_id=CLIENT_ID&response_type=TYPE&state=RANDOM_STRING&redirect_uri=URI&duration=DURATION&scope=SCOPE_STRING
