twitter:
  api_key: "yourKey"
  api_secret: "yourSecret"
  access_token: "yourToken"
  access_token_secret: "yourTokenSecret"
  app_auth_url: "https://api.twitter.com/oauth2/token"
  request_token_url: "https://api.twitter.com/oauth/request_token"
  authorize_secure_url: "https://api.twitter.com/oauth/authorize"
  access_token_url: "https://api.twitter.com/oauth/access_token"
  searchTerms:
    - "bitcoin,btc"
    - "litecoin,ltc"
    - "ardor,ardr"
    - "augur,$rep"
    - "belacoin,#bela,$bela"
    - "bitcoindark,btcd"
    - "bitcoinplus,xbc"
    - "bitcrystals,bcy"
    - "bitshares,$bts"
    - "bitmark,btm"
    - "bytecoin,bcn"
    - "#burst, $burst"
    - "clams,clam"
    - "dash"
    - "decred,dcr"
    - "digibyte,dgb"
    - "dnotes,$note"
    - "dogecoin,$doge"
    - "einsteinium,$emc2"
    - "ethereum classic,$etc"
    - "ethereum,eth"
    - "expanse,$exp"
    - "factom,$fct"
    - "florincoin,$flo"
    - "foldingcoin,$fldc"
    - "gameCredits"
    - "golem,$gnt"
    - "gridcoin,$grc"
    - "huntercoin,$huc"
    - "monero,$mnr"
    - "lbry,lbc,lbrycredits"
    - "lisk,$lsk"
    - "maidsafecoin,maidsafe,$maid"
    - "monero,$xmr"
    - "namecoin,$nmc"
    - "nautiluscoin,$naut"
    - "navcoin,$nav"
    - "#nem,$xem"
    - "neoscoin,$neos"
    - "nexium,$nxc"
    - "$nxt"
    - "omni"
    - "pascalcoin,$pasc"
    - "peercoin,$ppc"
    - "pinkcoin,$pink"
    - "potcoin,$pot"
    - "primecoin,$xpm"
    - "radium,$rads"
    - "riecoin,$ric"
    - "ripple,$xrp"
    - "siacoin,$sc"
    - "steem"
    - "steemdollars,$sbd"
    - "stellar,$str"
    - "storjcoin,sjcx"
    - "stratis,$strat"
    - "synero,$amp"
    - "syscoin,$sys"
    - "vericoin,$vrc"
    - "vertcoin,$vtc"
    - "viacoin,$via"
    - "zcash,$zec"