facebook:

medium:

reddit:

slack:

twitter:
  api_key: ""
  api_secret: ""
  access_token: ""
  access_token_secret: ""
  app_auth_url: https://api.twitter.com/oauth2/token
  request_token_url: https://api.twitter.com/oauth/request_token
  authorize_secure_url: https://api.twitter.com/oauth/authorize
  access_token_url: https://api.twitter.com/oauth/access_token

youtube:


